import streamlit as st
import pandas as pd
from src.ui.theme import apply_theme

st.set_page_config(page_title="Timeline Preview | ExplainInk AI", layout="wide")
apply_theme()

st.markdown("<h2>Timeline Preview Engine</h2>", unsafe_allow_html=True)
st.markdown("<p style='color: var(--muted-text);'>Review exact word-level synchronization between speech and generated handwriting.</p>", unsafe_allow_html=True)

if not st.session_state.get('project'):
    st.warning("Please initialize a project from the Upload page first.")
    st.stop()
    
project = st.session_state.project

if not project.timeline or not project.timeline.actions:
    st.info("No timeline events generated yet. Please run the AI Planner from the Workspace page.")
    st.stop()

# Build the display dataframe
data = []
for idx, action in enumerate(project.timeline.actions):
    data.append({
        "Step": idx + 1,
        "Start Time (s)": round(action.start_time, 2),
        "End Time (s)": round(action.end_time, 2),
        "Spoken Phrase": action.spoken_phrase if action.spoken_phrase else "—",
        "Rendered Text": action.text if action.text else "—",
        "Animation Type": action.action_type
    })

df = pd.DataFrame(data)

st.markdown("### Synchronization Details")
st.dataframe(
    df,
    use_container_width=True,
    column_config={
        "Step": st.column_config.NumberColumn("Step", width="small"),
        "Start Time (s)": st.column_config.NumberColumn("Start Time (s)", format="%.2f", width="small"),
        "End Time (s)": st.column_config.NumberColumn("End Time (s)", format="%.2f", width="small"),
        "Spoken Phrase": st.column_config.TextColumn("Spoken Phrase (Audio)", width="medium"),
        "Rendered Text": st.column_config.TextColumn("Rendered Text (Video)", width="medium"),
        "Animation Type": st.column_config.TextColumn("Animation", width="small"),
    },
    hide_index=True
)

st.markdown("---")
st.markdown("### Preview Video (Static Sync)")
st.info("This preview relies on the exact word-level timestamps generated by Faster-Whisper. Any delays in rendering are calculated progressively to match the spoken phrase duration perfectly. No pink highlight regions are generated.")
